services:
  db:
    container_name: 'job-database'
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=${POSTGRES_DB_NAME}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "${POSTGRES_DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network
  app:
    container_name: 'job-app'
    build: .
    environment:
      - 'SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}'
      - 'SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}'
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${POSTGRES_DB_NAME}'
      - 'SPRING_JPA_HIBERNATE_DDL_AUTO=update'
      - 'AWS_REGION=eu-north-1'
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
networks:
  app-network: